name: Frontend Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy_to_vercel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build 
      
    - name: Deploy to Vercel
      run: vercel --prod 
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  


    - name: Run pre-commit hooks
      run: pre-commit run --all-files
